version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2048M'
        reservations:
          cpus: '0.5'
          memory: '1024M'